<input type="file"{+START_IF_PASSED,ID} id="{ID*}"{+END}{+START_IF_NON_PASSED,ID} id="{NAME*}"{+END} name="{NAME*}"{+START,IF_PASSED_AND_TRUE,REQUIRED} required="required"{+END}{+START,IF_PASSED,SIZE} size="{SIZE*}"{+END}{+START,IF_PASSED,CLASS} class="{CLASS*}"{+END}{+START,IF_PASSED,TABINDEX} tabindex="{TABINDEX*}"{+END}{+START,IF_PASSED,EXTRA} {EXTRA}{+END} />

{+START,INCLUDE,forms/_INPUT_FIELD}{+END}
