<input type="date"{+START,IF_PASSED,ID} id="{ID*}"{+END}{+START,IF_NON_PASSED,ID} id="{NAME*}"{+END} name="{NAME*}" value="{VALUE*}"{+START,IF_PASSED_AND_TRUE,REQUIRED} required="required"{+END}{+START,IF_PASSED,MIN} min="{MIN*}"{+END}{+START,IF_PASSED,MIN} max="{MAX*}"{+END}{+START,IF_PASSED,CLASS} class="{CLASS*}"{+END}{+START,IF_PASSED_AND_TRUE,DISABLED} disabled="disabled"{+END}{+START,IF_PASSED_AND_TRUE,READONLY} readonly="readonly"{+END}{+START,IF_PASSED,TABINDEX} tabindex="{TABINDEX*}"{+END}{+START,IF_PASSED,EXTRA} {EXTRA}{+END} />

{+START,INCLUDE,forms/_INPUT_FIELD}{+END}
