<input type="checkbox"{+START_IF_PASSED,ID} id="{ID*}"{+END}{+START_IF_NON_PASSED,ID} id="{NAME*}"{+END} name="{NAME*}" value="1"{+START,IF_PASSED_AND_TRUE,CHECKED} checked="checked"{+END}{+START,IF_PASSED,CLASS} class="{CLASS*}"{+END}{+START,IF_PASSED_AND_TRUE,DISABLED} disabed="disabled"{+END}{+START,IF_PASSED_AND_TRUE,READONLY} readonly="readonly"{+END}{+START,IF_PASSED,TABINDEX} tabindex="{TABINDEX*}"{+END}{+START,IF_PASSED,EXTRA} {EXTRA}{+END} />

{+START,INCLUDE,_INPUT_FIELD}REQUIRED=0{+END}
